# Generated by Django 5.1.4 on 2025-01-20 23:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Difficulty rating from 1 (easiest) to 5 (hardest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at', 'recipe'], name='recipes_com_created_0ce5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='recipes_rec_created_57db65_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author'], name='recipes_rec_author__e2628b_idx'),
        ),
        migrations.AddField(
            model_name='difficultyrating',
            name='rating_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='difficultyrating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_ratings', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='difficultyrating',
            index=models.Index(fields=['recipe', 'rating_author'], name='recipes_dif_recipe__05c077_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='difficultyrating',
            unique_together={('recipe', 'rating_author')},
        ),
    ]
